name: Run Stremio with Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  stremio:
    runs-on: ubuntu-latest

    steps:
      - name: Start Stremio Docker container
        run: |
          docker run -d \
            --name stremio-server \
            -p 3000:3000 \
            stremio/stremio-server

      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Start Cloudflare Tunnel to Stremio
        run: cloudflared tunnel --url http://localhost:3000
